# Generated by Django 6.0.2 on 2026-04-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección del proveedor', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Nombre de la persona de contacto', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, help_text='Email del proveedor', max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de teléfono del proveedor', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, help_text='Sitio web del proveedor', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Teléfono, email o datos de contacto (legacy)', max_length=255),
        ),
    ]
