# Generated by Django 6.0.2 on 2026-04-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_supplier_address_supplier_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del producto', null=True, upload_to='products/'),
        ),
    ]
