# Generated by Django 6.0.2 on 2026-05-12 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_replace_image_imagefield_with_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variation_type', models.CharField(choices=[('color', 'Color'), ('size', 'Talla'), ('weight', 'Peso'), ('material', 'Material'), ('other', 'Otro')], help_text='Tipo de variación', max_length=15)),
                ('variation_value', models.CharField(help_text='Valor de la variación', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product')),
            ],
            options={
                'verbose_name': 'Variación de producto',
                'verbose_name_plural': 'Variaciones de producto',
                'db_table': 'product_variation',
                'unique_together': {('product', 'variation_value')},
            },
        ),
    ]
