# Generated by Django 6.0.2 on 2026-06-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs Review'), ('active', 'Active')], default='draft', help_text='Estado del producto', max_length=20),
        ),
    ]
