# Generated by Django 6.0.2 on 2026-05-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_tendered',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo entregado por el cliente', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cambio devuelto al cliente', max_digits=12, null=True),
        ),
    ]
