# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_amount_tendered_sale_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='Identificador externo/ticket de la venta',
                max_length=64,
            ),
        ),
    ]
