# Generated by Django 6.0.2 on 2026-05-12 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('cash', 'Contado'), ('credit', 'Fiado/Crédito'), ('layaway', 'Apartado')], default='cash', help_text='Tipo de venta (contado, fiado, apartado)', max_length=15),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('other', 'Otro')], default='cash', max_length=15),
        ),
    ]
