# Generated by Django 6.0.2 on 2026-04-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='default_cash',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fondo inicial sugerido para apertura de caja', max_digits=12),
        ),
        migrations.AddField(
            model_name='store',
            name='is_first_setup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='niche',
            field=models.CharField(blank=True, choices=[('ELECTRONICA', 'Electrónica'), ('ABARROTES', 'Abarrotes'), ('FARMACIA', 'Farmacia'), ('FERRETERIA', 'Ferretería')], help_text='Nicho de negocio para categorías sugeridas', max_length=20),
        ),
    ]
