# Generated by Django 6.0.2 on 2026-05-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_store_default_cash_store_is_first_setup_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='niche',
            field=models.CharField(blank=True, choices=[('ELECTRONICA', 'Electrónica'), ('ABARROTES', 'Abarrotes'), ('FARMACIA', 'Farmacia'), ('FERRETERIA', 'Ferretería'), ('MASCOTAS', 'Mascotas y Veterinaria'), ('BELLEZA', 'Belleza y Estética')], help_text='Nicho de negocio para categorías sugeridas', max_length=20),
        ),
    ]
