# Generated by Django 6.0.2 on 2026-05-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_store_niche'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='currency_symbol',
            field=models.CharField(default='$ MXN', help_text='Simbolo de moneda', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Direccion de la tienda', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Telefono de la tienda', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='country_code',
            field=models.CharField(blank=True, default='+52', help_text='Codigo de pais', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='ticket_message',
            field=models.TextField(blank=True, default='Gracias por su preferencia!'),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
