# Generated by Django 6.0.2 on 2026-04-04 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Identificador único para Pusher/WebSocket', max_length=100, unique=True)),
                ('total_temp', models.DecimalField(decimal_places=2, default=0, help_text='Total temporal del carrito', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_carts', to='accounts.store')),
                ('user', models.ForeignKey(help_text='Usuario que está llenando el carrito', on_delete=django.db.models.deletion.CASCADE, related_name='active_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito Activo',
                'verbose_name_plural': 'Carritos Activos',
                'db_table': 'active_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad en el carrito')),
                ('unit_price_at_time', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento de agregar', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.activecart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Item del Carrito',
                'verbose_name_plural': 'Items del Carrito',
                'db_table': 'cart_item',
            },
        ),
        migrations.AddIndex(
            model_name='activecart',
            index=models.Index(fields=['store'], name='active_cart_store_i_13ee58_idx'),
        ),
        migrations.AddIndex(
            model_name='activecart',
            index=models.Index(fields=['user'], name='active_cart_user_id_0edce3_idx'),
        ),
        migrations.AddIndex(
            model_name='activecart',
            index=models.Index(fields=['session_id'], name='active_cart_session_aac567_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
