# Generated by Django 6.0.2 on 2026-04-04 17:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='NULL si el turno sigue abierto', null=True)),
                ('starting_cash', models.DecimalField(decimal_places=2, help_text='Fondo de caja inicial', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_by', models.ForeignKey(help_text='Usuario que abrió la caja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_cash_shifts', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_shifts', to='accounts.store')),
            ],
            options={
                'verbose_name': 'Turno de Caja',
                'verbose_name_plural': 'Turnos de Caja',
                'db_table': 'cash_shift',
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('in', 'Entrada (IN)'), ('out', 'Salida (OUT)')], help_text='IN (Entrada) / OUT (Salida)', max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.CharField(help_text='Razón (Ej: Venta #10, Pago internet)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='expenses.cashshift')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'cash_movement',
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la categoría (Ej: Servicios, Nómina, Compras)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='accounts.store')),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gasto',
                'db_table': 'expense_category',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('received', 'Recibida'), ('cancelled', 'Cancelada')], default='pending', help_text='Estado: PENDING, RECEIVED, CANCELLED', max_length=15)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Costo total', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='accounts.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='products.supplier')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'db_table': 'purchase_order',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del gasto', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta')], help_text='Método de pago: CASH, TRANSFER, CARD', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_shift', models.ForeignKey(blank=True, help_text='Opcional: Nulo si se pagó por banco', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.cashshift')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.store')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensecategory')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Opcional: Si es gasto de mercancía', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.purchaseorder')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'db_table': 'expense',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Costo unitario', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='products.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.purchaseorder')),
            ],
            options={
                'verbose_name': 'Item de Orden de Compra',
                'verbose_name_plural': 'Items de Órdenes de Compra',
                'db_table': 'purchase_order_item',
            },
        ),
        migrations.AddIndex(
            model_name='cashshift',
            index=models.Index(fields=['store'], name='cash_shift_store_i_8e2dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='cashshift',
            index=models.Index(fields=['opened_at'], name='cash_shift_opened__7b4198_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['cash_shift'], name='cash_moveme_cash_sh_220e72_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['created_at'], name='cash_moveme_created_a286ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('store', 'name')},
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['store'], name='purchase_or_store_i_a69e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchase_or_status_86ae3f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['store'], name='expense_store_i_7f0f63_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='expense_categor_592b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_at'], name='expense_created_0a6070_idx'),
        ),
    ]
