# Generated by Django 6.0.2 on 2026-03-26 08:09

import django.db.models.deletion
import expenses.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('starting_cash', models.DecimalField(decimal_places=2, help_text='Efectivo inicial', max_digits=12)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo esperado', max_digits=12, null=True)),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo contado', max_digits=12, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, help_text='Diferencia', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas del cierre')),
                ('user', models.ForeignKey(help_text='Cajero', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno de Caja',
                'verbose_name_plural': 'Turnos de Caja',
                'db_table': 'cash_shift',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del gasto', max_digits=12, validators=[expenses.validators.validate_amount_positive])),
                ('category', models.CharField(choices=[('servicios', 'Servicios (Luz, Agua, Internet)'), ('nomina', 'Nómina / Sueldos'), ('proveedores', 'Pago a Proveedores'), ('inventario', 'Inventario / Reabastecimiento'), ('varios', 'Gastos Varios')], help_text='Categoría del gasto', max_length=20)),
                ('description', models.CharField(help_text='Descripción', max_length=255)),
                ('receipt_url', models.URLField(blank=True, help_text='URL del recibo', max_length=800, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('cash_shift', models.ForeignKey(blank=True, help_text='Turno de caja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.cashshift')),
                ('supplier', models.ForeignKey(blank=True, help_text='Proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.supplier')),
                ('user', models.ForeignKey(help_text='Usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'db_table': 'expense',
            },
        ),
        migrations.AddIndex(
            model_name='cashshift',
            index=models.Index(fields=['opened_at'], name='cash_shift_opened__7b4198_idx'),
        ),
        migrations.AddIndex(
            model_name='cashshift',
            index=models.Index(fields=['user'], name='cash_shift_user_id_b9493b_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'date'], name='expense_categor_c5603d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user'], name='expense_user_id_2c0bb9_idx'),
        ),
    ]
