# Generated by Django 6.0.2 on 2026-02-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Mi Tienda', max_length=200)),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('ticket_message', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, max_length=800, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Negocio',
            },
        ),
    ]
