# Generated by Django 6.0.2 on 2026-03-06 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_category_user_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
