# Generated by Django 6.0.2 on 2026-03-08 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_storeprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSessionCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_data', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
