# Generated by Django 6.0.2 on 2026-03-15 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sale_amount_paid_sale_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cash_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cashshift'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.supplier'),
        ),
        migrations.AlterField(
            model_name='client',
            name='plan',
            field=models.CharField(choices=[('basico', 'Básico'), ('pro', 'Pro')], default='basico', max_length=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('servicios', 'Servicios (Luz, Agua, Internet)'), ('nomina', 'Nómina / Sueldos'), ('proveedores', 'Pago a Proveedores'), ('inventario', 'Inventario / Reabastecimiento'), ('varios', 'Gastos Varios')], max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Venta'), ('restock', 'Reabastecimiento'), ('adjust', 'Ajuste de Inventario')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('cash_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.cashshift')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='api.expense')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
