# Generated by Django 6.0.2 on 2026-03-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_expense_cash_shift_expense_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='is_first_setup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='ticket_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
