# Generated by Django 6.0.2 on 2026-05-07 04:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_store_settings_fields'),
        ('carts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activecart',
            name='is_parked',
            field=models.BooleanField(default=False, help_text='Indica si el carrito está aparcado (guardado para después)'),
        ),
        migrations.AddField(
            model_name='activecart',
            name='parked_at',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora cuando el carrito fue aparcado', null=True),
        ),
        migrations.AddIndex(
            model_name='activecart',
            index=models.Index(fields=['is_parked', 'user'], name='active_cart_is_park_48a4fd_idx'),
        ),
    ]
