# Generated by Django 6.0.2 on 2026-03-26 08:09

import django.db.models.deletion
import inventory.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Venta'), ('restock', 'Reabastecimiento'), ('adjust', 'Ajuste de Inventario')], help_text='Tipo de movimiento', max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad', validators=[inventory.validators.validate_quantity_positive])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario', max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo total', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notas')),
                ('cash_shift', models.ForeignKey(help_text='Turno de caja', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='expenses.cashshift')),
                ('product', models.ForeignKey(help_text='Producto', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product')),
                ('user', models.ForeignKey(help_text='Usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'inventory_movement',
                'indexes': [models.Index(fields=['movement_type', 'created_at'], name='inventory_m_movemen_15f5ee_idx'), models.Index(fields=['product'], name='inventory_m_product_9d6ead_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Entrada (Compra/Proveedor)'), ('out', 'Salida (Venta/Manual)'), ('adjustment', 'Ajuste de Inventario'), ('waste', 'Merma / Dañado')], help_text='Tipo de transacción', max_length=15)),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad', validators=[inventory.validators.validate_quantity_positive])),
                ('reason', models.CharField(blank=True, help_text='Razón del movimiento', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Producto', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.product')),
                ('user', models.ForeignKey(help_text='Usuario que realizó el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción de Inventario',
                'verbose_name_plural': 'Transacciones de Inventario',
                'db_table': 'inventory_transaction',
                'indexes': [models.Index(fields=['transaction_type', 'created_at'], name='inventory_t_transac_87cb76_idx'), models.Index(fields=['product'], name='inventory_t_product_4a7afe_idx')],
            },
        ),
    ]
