# Generated by Django 6.0.2 on 2026-04-04 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('sale', 'Venta'), ('purchase', 'Compra a Proveedor'), ('adjustment', 'Ajuste de Inventario'), ('return', 'Devolución')], help_text='Tipo de movimiento', max_length=15)),
                ('quantity', models.IntegerField(help_text='Cantidad (negativo para salida, positivo para entrada)')),
                ('stock_before', models.PositiveIntegerField(help_text='Stock antes del movimiento')),
                ('stock_after', models.PositiveIntegerField(help_text='Stock exacto resultante después del movimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.product')),
                ('user', models.ForeignKey(help_text='Usuario que realizó el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'inventory_movement',
                'indexes': [models.Index(fields=['product'], name='inventory_m_product_9d6ead_idx'), models.Index(fields=['movement_type', 'created_at'], name='inventory_m_movemen_15f5ee_idx')],
            },
        ),
    ]
