# Generated by Django 6.0.2 on 2026-06-29 02:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(help_text='Código de barras global', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Nombre del producto', max_length=255)),
                ('brand', models.CharField(blank=True, help_text='Marca del producto', max_length=255)),
                ('category', models.CharField(blank=True, help_text='Categoría del producto', max_length=255)),
                ('image_url', models.URLField(blank=True, help_text='URL de la imagen del producto', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto Global',
                'verbose_name_plural': 'Productos Globales',
                'db_table': 'global_product',
            },
        ),
    ]
