# Generated by Django 6.0.2 on 2026-05-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashshift',
            name='actual_cash',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo real contado al cierre', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diferencia (actual_cash - expected_cash)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='expected_cash',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo esperado al cierre', max_digits=12, null=True),
        ),
    ]
