# Generated by Django 6.0.2 on 2026-04-04 17:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('expenses', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('paid', 'Pagada'), ('partial', 'Pago Parcial'), ('cancelled', 'Cancelada')], default='paid', help_text='Estado de la venta', max_length=15)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total a cobrar', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Suma de abonos + pago inicial', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_shift', models.ForeignKey(blank=True, help_text='Turno de caja donde se ingresó el dinero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='expenses.cashshift')),
                ('customer', models.ForeignKey(blank=True, help_text='Cliente (opcional para venta rápida)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='accounts.client')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.store')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'sale',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad vendida')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento de la venta', max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Costo unitario al momento de la venta', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Item de Venta',
                'verbose_name_plural': 'Items de Venta',
                'db_table': 'sale_item',
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del abono', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_payments', to='expenses.cashshift')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Ventas',
                'db_table': 'sale_payment',
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store'], name='sale_store_i_d9f9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sale_status_fc4a69_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='sale_created_6032a4_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['sale'], name='sale_paymen_sale_id_babdb2_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['created_at'], name='sale_paymen_created_733f0d_idx'),
        ),
    ]
