# Generated by Django 6.0.2 on 2026-03-26 08:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='ID único de transacción', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completada'), ('pending', 'Pendiente'), ('cancelled', 'Cancelada'), ('credit', 'Crédito'), ('layaway', 'Apartado')], default='completed', help_text='Estado de la venta', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total de la venta', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(blank=True, help_text='Nombre del cliente', max_length=200, null=True)),
                ('customer_phone', models.CharField(blank=True, help_text='Teléfono del cliente', max_length=20, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, help_text='Monto pagado', max_digits=12, null=True)),
                ('user', models.ForeignKey(help_text='Usuario que realizó la venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'sale',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Snapshot del nombre del producto', max_length=250)),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad vendida')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario', max_digits=10)),
                ('product', models.ForeignKey(help_text='Producto vendido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('sale', models.ForeignKey(help_text='Venta asociada', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Item de Venta',
                'verbose_name_plural': 'Items de Venta',
                'db_table': 'sale_item',
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del abono', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(help_text='Venta asociada', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
                ('user', models.ForeignKey(help_text='Usuario que realizó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Ventas',
                'db_table': 'sale_payment',
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['transaction_id'], name='sale_transac_36bf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sale_status_fc4a69_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='sale_created_6032a4_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['sale', 'created_at'], name='sale_paymen_sale_id_3d5064_idx'),
        ),
    ]
